/*
Test generated by RoostGPT for test aman321 using AI Type Open AI and AI Model gpt-4

1. **Scenario**: Verify the `toString()` method returns the correct string representation of the `Admin` class with all attributes populated correctly.
   - **Expected Result**: The returned string should be in the format: "Admin [adminId= {adminId}, adminName= {adminName}, adminEmail= {adminEmail}, adminPassword= {adminPassword}, adminNumber= {adminNumber}]"

2. **Scenario**: Verify the `toString()` method when the `Admin` class attributes have null values.
   - **Expected Result**: The returned string should show null values in the respective places: "Admin [adminId= null, adminName= null, adminEmail= null, adminPassword= null, adminNumber= null]"

3. **Scenario**: Verify the `toString()` method when the `Admin` class attributes have empty strings.
   - **Expected Result**: The returned string should show empty values in the respective places: "Admin [adminId= , adminName= , adminEmail= , adminPassword= , adminNumber= ]"

4. **Scenario**: Verify the `toString()` method when the `Admin` class attributes have special characters or numbers.
   - **Expected Result**: The returned string should correctly display the special characters or numbers in the respective places.

5. **Scenario**: Verify the `toString()` method when the `Admin` class attributes have maximum allowed length values (boundary test).
   - **Expected Result**: The returned string should correctly display the attributes with maximum length values.

6. **Scenario**: Verify the `toString()` method when the `Admin` class attributes have values more than the maximum allowed length (boundary test).
   - **Expected Result**: Depending on the implementation, it should either truncate the values and display up to maximum allowed length or throw an exception.

7. **Scenario**: Verify the `toString()` method when the `Admin` class attributes have minimum allowed length values (boundary test).
   - **Expected Result**: The returned string should correctly display the attributes with minimum length values.

8. **Scenario**: Verify the `toString()` method's functionality with concurrent requests (concurrency test).
   - **Expected Result**: The `toString()` method should correctly return the string representation of the `Admin` class for multiple concurrent requests without any data inconsistencies or race conditions.
*/
import org.springframework.beans.factory.annotation.Value;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

@Entity
public class Admin {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int adminId;

    @NotNull
    @Size(min = 2, max = 30)
    private String adminName;

    @Email
    private String adminEmail;

    @NotNull
    @Size(min = 8)
    private String adminPassword;
    
    private String adminNumber;

    public int getAdminId() {
        return adminId;
    }

    public void setAdminId(int adminId) {
        this.adminId = adminId;
    }

    public String getAdminName() {
        return adminName;
    }

    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    public String getAdminEmail() {
        return adminEmail;
    }

    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }

    public String getAdminPassword() {
        return adminPassword;
    }

    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }

    public String getAdminNumber() {
        return adminNumber;
    }

    public void setAdminNumber(String adminNumber) {
        this.adminNumber = adminNumber;
    }

    @Override
    public String toString() {
        return "Admin [adminId=" + adminId + ", adminName=" + adminName + ", adminEmail=" + adminEmail + ", adminPassword=" + adminPassword + ", adminNumber=" + adminNumber + "]";
    }
}
