# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /accounts_patch for http method type PATCH 
# RoostTestHash=2758affb7e
# 
# 

# ********RoostGPT********
Feature: Login to existing Account

Background:
  * def urlBase = karate.properties['url.base'] || 'http://localhost:8080'
  * url urlBase

Scenario Outline: Test Login Functionality
  Given path '/accounts'
  And request { "email": "<email>" }
  When method post
  Then match responseStatus == <status>
  And match responseHeaders['api-version'] == '1.0.0'
  And match response contains { "description": '#string', "error": '#string' }
  Examples:
    | email                          | status |
    | 'testuser@domain.com'          | 200    |
    | 'invalidemail'                 | 400    |
    | ''                             | 400    |
