# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /apikeys/{id}_delete for http method type DELETE 
# RoostTestHash=4affc26394
# 
# 

# ********RoostGPT********
Feature: API keys

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']
  * configure headers = { ApiKeyAuth: '#(authToken)' }

Scenario Outline: Validate GET /apikeys/{id} endpoint

  Given path 'apikeys', '<id>'
  When method get
  Then status 200

  And match responseHeaders == { 'api-version': '1.0.0' }

  Examples:
    | id   |
    | 3e37ac1a-a89f-47b0-b3fa-ac5f787da1ad |

Scenario Outline: Validate error responses for GET /apikeys/{id} endpoint

  Given path 'apikeys', '<id>'
  When method get
  Then status <status>

  And match responseHeaders == { 'api-version': '1.0.0' }
  
  And match response contains { 'error': '<error>', 'description': '<description>' }

  Examples:
    | id   | status | error            | description                  |
    | 123  | 400    | error/code       | Descriptive Error Message  |
    | 123  | 401    | validation/email-pattern | Descriptive Error Message  |
