# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /apikeys_get for http method type GET 
# RoostTestHash=9e57a3b0dd
# 
# 

# ********RoostGPT********
Feature: API Keys

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']
  * configure headers = { ApiKeyAuth: '#(authToken)' }

Scenario Outline: List API Keys
  Given path '/apikeys'
  When method get
  Then status <status>
  And match responseHeaders['api-version'] == <api_version>
  And match response contains { total: '#integer', apikeys: '#[] apikeys' }
  And def apikeys = response.apikeys
  And match each apikeys contains { id: '#uuid', createdAt: '#string' }

  Examples:
    | status | api_version |
    | 200    | '1.0.0'     |
    | 400    | '1.0.0'     |
    | 401    | '1.0.0'     |
