# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /authorizations/{id}_delete for http method type DELETE 
# RoostTestHash=cb128291e8
# 
# 

# ********RoostGPT********
Feature: Remove Authorized Account

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def headers = { 'ApiKeyAuth': '#(karate.properties["AUTH_TOKEN"])' }

Scenario Outline: Validate Successful Operation
  Given path '/authorizations/', '<id>'
  And headers headers
  When method delete
  Then status 200
  And match responseHeaders['api-version'] == '1.0.0'

Examples:
  | id |
  | '123e4567-e89b-12d3-a456-426614174000' |
  | '123e4567-e89b-12d3-a456-426614174001' |

Scenario Outline: Validate Bad Request
  Given path '/authorizations/', '<id>'
  And headers headers
  When method delete
  Then status 400
  And match responseHeaders['api-version'] == '1.0.0'
  And match response == { description: '#string', error: '#string' }

Examples:
  | id |
  | '123e4567-e89b-12d3-a456-426614174000' |
  | '123e4567-e89b-12d3-a456-426614174001' |

Scenario Outline: Validate Authentication Required
  Given path '/authorizations/', '<id>'
  And headers headers
  When method delete
  Then status 401
  And match responseHeaders['api-version'] == '1.0.0'
  And match response == { description: '#string', error: '#string' }

Examples:
  | id |
  | '123e4567-e89b-12d3-a456-426614174000' |
  | '123e4567-e89b-12d3-a456-426614174001' |
