# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /credentials_get for http method type GET 
# RoostTestHash=c5011f3c64
# 
# 

# ********RoostGPT********
Feature: All credentials in my Wallet

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * configure headers = { ApiKeyAuth: '#(karate.properties['AUTH_TOKEN'])' }

Scenario Outline: Validate successful operation with different size and offset
  Given path '/credentials'
  And param size = '<size>'
  And param offset = '<offset>'
  When method get
  Then status 200
  And match responseHeaders['api-version'] == '1.0.0'
  And match responseHeaders['page-size'] == '<size>'
  And match responseHeaders['page-offset'] == '<offset>'
  And match response.total == '#integer'
  And match each response.credentials contains 
    { 
      id: '#string', 
      format: '#string', 
      credential: '#string', 
      status: '#string', 
      statusUpdatedAt: '#string', 
      createdAt: '#string' 
    }

  Examples:
    | size | offset |
    | 20   | 0      |
    | 30   | 10     |
    | 40   | 20     |

Scenario: Validate bad request
  Given path '/credentials'
  And param size = 'test'
  When method get
  Then status 400
  And match responseHeaders['api-version'] == '1.0.0'
  And match response == { error: '#string', description: '#string' }

Scenario: Validate authentication required
  Given path '/credentials'
  And configure headers = { ApiKeyAuth: 'InvalidToken' }
  When method get
  Then status 401
  And match responseHeaders['api-version'] == '1.0.0'
  And match response == { error: '#string', description: '#string' }
