# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /credentials/{id}_get for http method type GET 
# RoostTestHash=c02d3561ab
# 
# 

# ********RoostGPT********
Feature: Credentials API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authHeader = { 'ApiKeyAuth': '#(karate.properties['AUTH_TOKEN'])' }

Scenario Outline: Get credential from my Wallet
  Given path 'credentials', '<id>'
  And headers authHeader
  When method get
  Then status 200
  And match response contains {createdAt: '#string', credential: '#string', format: '#string', id: '#string', status: '#string', statusUpdatedAt: '#string'}
  And match responseHeaders contains { 'api-version': '#string' }

Examples:
  | id |
  | '123e4567-e89b-12d3-a456-426614174000' |
  | '123e4567-e89b-12d3-a456-426614174001' |
  | '123e4567-e89b-12d3-a456-426614174002' |

Scenario Outline: Get credential from my Wallet with Bad Request
  Given path 'credentials', '<invalid_id>'
  And headers authHeader
  When method get
  Then status 400
  And match response contains {description: '#string', error: '#string'}
  And match responseHeaders contains { 'api-version': '#string' }

Examples:
  | invalid_id |
  | 'invalid-id' |
  | '' |
  | '123' |

Scenario: Get credential from my Wallet with Unauthorized Request
  Given path 'credentials', '123e4567-e89b-12d3-a456-426614174000'
  And headers { 'ApiKeyAuth': 'invalid_token' }
  When method get
  Then status 401
  And match response contains {description: '#string', error: '#string'}
  And match responseHeaders contains { 'api-version': '#string' }
