# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /credentials/{id}_delete for http method type DELETE 
# RoostTestHash=f1fc1d06f7
# 
# 

# ********RoostGPT********
Feature: Delete one credential from my Wallet

Background: 
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']
  * def headers = { 'ApiKeyAuth': '#(authToken)' }

Scenario Outline: Delete credential with valid id
  Given path 'credentials', '<id>'
  And headers headers
  When method delete
  Then status 200
  And match responseHeaders['api-version'] == '1.0.0'

Examples:
  | id |
  | '3fa85f64-5717-4562-b3fc-2c963f66afa6' |

Scenario Outline: Delete credential with invalid id
  Given path 'credentials', '<id>'
  And headers headers
  When method delete
  Then status 400
  And match responseHeaders['api-version'] == '1.0.0'
  And match response contains { description: '#string', error: '#string' }

Examples:
  | id |
  | '123' |

Scenario Outline: Delete credential with missing auth token
  Given path 'credentials', '<id>'
  When method delete
  Then status 401
  And match responseHeaders['api-version'] == '1.0.0'
  And match response contains { description: '#string', error: '#string' }

Examples:
  | id |
  | '3fa85f64-5717-4562-b3fc-2c963f66afa6' |
