# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /errors_get for http method type GET 
# RoostTestHash=588ae64bad
# 
# 

# ********RoostGPT********
Feature: Errors API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
  * configure headers = { 'Authorization': '#('Bearer ' + AUTH_TOKEN) }

Scenario: Test GET /errors endpoint
  Given path '/errors'
  When method get
  Then status 200
  And match header api-version == '1.0.0'
  And match response contains { 'error': '#string', 'description': '#string' }
  And match response contains { 'error': '#regex ^validation/.*', 'description': '#string', 'value': '#?string', 'field': '#?string', 'schema_field': '#?string' }
