# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /kvk/zoeken_get for http method type GET 
# RoostTestHash=2acea70323
# 
# 

# ********RoostGPT********
Feature: KvK Zoeken API feature

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def auth_token = karate.properties['AUTH_TOKEN']
  * configure headers = {ApiKeyAuth: '#(auth_token)'}

Scenario Outline: Testing GET method with various combinations of request parameters

  Given path '/kvk/zoeken'
  And param kvkNummer = '<kvkNummer>'
  And param vestigingsnummer = '<vestigingsnummer>'
  And param handelsnaam = '<handelsnaam>'
  When method get
  Then status 200
  And match response contains '<response>'

  Examples:
    | kvkNummer | vestigingsnummer | handelsnaam | response |
    | '123456'  | '001'            | 'TestName'  | 'See kvk OAS specs' |
    | '654321'  | '002'            | 'TestName2' | 'See kvk OAS specs' |
    | '789012'  | '003'            | 'TestName3' | 'See kvk OAS specs' |
