# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /logout_post for http method type POST 
# RoostTestHash=64d33906e5
# 
# 

# ********RoostGPT********
Feature: Logout API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Logout - <scenario>
  Given def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
  And configure headers = { ApiKeyAuth: '#(AUTH_TOKEN)' }
  And path '/logout'
  When method delete
  Then status <status>
  And match header api-version == '1.0.0'
  And match response == <response>

Examples:
  | scenario               | status | response                                                                                                         |
  | 'successful operation' | 200    | {}                                                                                                               |
  | 'bad request'          | 400    | { description: '#string', error: '#regex[^validation/.*$]', value: '#notnull', field: '#string', schema_field: '#string' } |
