# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /me_get for http method type GET 
# RoostTestHash=ae6b8ce5ab
# 
# 

# ********RoostGPT********
Feature: Account

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def AuthToken = karate.properties['AUTH_TOKEN']
  * configure headers = { ApiKeyAuth: '#(AuthToken)' }

Scenario: Get Account Details
  Given path '/me'
  When method get
  Then status 200
  And match responseHeaders['api-version'] == '1.0.0'
  And match response == 
  """
  { 
    id: '#string', 
    did: '#string', 
    name: '#string', 
    image: '#string', 
    email: '#string', 
    settings: '#object', 
    createdAt: '#string', 
    updatedAt: '#string' 
  }
  """

Scenario: Get Account Details - Bad Request
  Given path '/me'
  When method get
  Then status 400
  And match responseHeaders['api-version'] == '1.0.0'
  And match response == 
  """
  { 
    error: '#string', 
    description: '#string' 
  }
  """

Scenario: Get Account Details - Authentication Required
  Given path '/me'
  When method get
  Then status 401
  And match responseHeaders['api-version'] == '1.0.0'
  And match response == 
  """
  { 
    error: '#string', 
    description: '#string' 
  }
  """
