# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /recipients/persons/{id}_patch for http method type PATCH 
# RoostTestHash=1416aa2295
# 
# 

# ********RoostGPT********
Feature: Recipient Person API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def auth_token = karate.properties['AUTH_TOKEN']
  * def Authorization = { 'ApiKeyAuth': '#(auth_token)' }

Scenario Outline: Update a Person
  Given path '/recipients/persons', '<id>'
  And request {initials:"<initials>", firstName:"<firstName>", middleName:"<middleName>", lastName:"<lastName>", birthDate:"<birthDate>", birthPlace:"<birthPlace>", phone:"<phone>", email:"<email>", postalCode:"<postalCode>", houseNumber:"<houseNumber>", houseNumberPostfix:"<houseNumberPostfix>", countryCode:"<countryCode>", reference:"<reference>"}
  And header Authorization = Authorization
  When method put
  Then status 200
  And match response contains {initials:"<initials>", firstName:"<firstName>", middleName:"<middleName>", lastName:"<lastName>", birthDate:"<birthDate>", birthPlace:"<birthPlace>", phone:"<phone>", email:"<email>", postalCode:"<postalCode>", houseNumber:"<houseNumber>", houseNumberPostfix:"<houseNumberPostfix>", countryCode:"<countryCode>", reference:"<reference>"}
  And match header api-version == '1.0.0'

Examples:
  | id  | initials | firstName | middleName | lastName | birthDate | birthPlace | phone | email   | postalCode | houseNumber | houseNumberPostfix | countryCode | reference |
  | '1' | 'ABC'    | 'John'    | 'M'        | 'Doe'    | '1990-01-01' | 'USA' | '1234567890' | 'john.doe@example.com' | '12345' | '1' | 'A' | 'US' | 'Ref123' |
