# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /recipients/branches/{id}/registrations_post for http method type POST 
# RoostTestHash=16a6858a84
# 
# 

# ********RoostGPT********
Feature: Recipient Branch API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
  * configure headers = { ApiKeyAuth: '#(AUTH_TOKEN)' }

Scenario Outline: Create new Registration for the Recipient
  Given path '/recipients/branches/', '<id>', '/registrations'
  And request {"reference": "<reference>", "startDate": "<startDate>", "endDate": "<endDate>", "credentialUrl": "<credentialUrl>"}
  When method post
  Then status 201
  And match responseHeaders['api-version'] == '1.0.0'
  And match responseHeaders['location'] == '#string'
  And match response ==
    """
    {
      "id": "#uuid",
      "reference": "#(reference)",
      "startDate": "#(startDate)",
      "endDate": "#(endDate)",
      "status": "active",
      "credentialUrl": "#(credentialUrl)",
      "suspendedUntil": "#null",
      "issuedAt": "#null",
      "createdAt": "#string",
      "updatedAt": "#string"
    }
    """

Examples:
  | id                                   | reference | startDate  | endDate    | credentialUrl                      |
  | '123e4567-e89b-12d3-a456-426655440000' | 'ref123'  | '2022-01-01' | '2022-12-31' | 'http://example.com/credentialUrl' |

Scenario Outline: Create new Registration for the Recipient - Negative Cases
  Given path '/recipients/branches/', '<id>', '/registrations'
  And request {"reference": "<reference>", "startDate": "<startDate>", "endDate": "<endDate>", "credentialUrl": "<credentialUrl>"}
  When method post
  Then status <status>
  And match responseHeaders['api-version'] == '1.0.0'
  And match response.error == "<error>"
  And match response.description == "<description>"

Examples:
  | id                                   | reference | startDate  | endDate    | credentialUrl                      | status | error                 | description               |
  | '123e4567-e89b-12d3-a456-426655440000' | 'ref123'  | '2022-01-01' | '2022-12-31' | 'http://example.com/credentialUrl' | 400    | 'validation/email-pattern' | 'Descriptive Error Message' |
  | '123e4567-e89b-12d3-a456-426655440000' | 'ref123'  | '2022-01-01' | '2022-12-31' | 'http://example.com/credentialUrl' | 401    | 'error/code'                 | 'Descriptive Error Message' |
