# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /recipients/persons/{id}/registrations_post for http method type POST 
# RoostTestHash=0973c499e9
# 
# 

# ********RoostGPT********
Feature: Recipient Person Registration

Background:
* def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
* url urlBase
* configure headers = { 'ApiKeyAuth': '#(karate.properties['AUTH_TOKEN'])' }

Scenario Outline: Create new Registration
    Given path 'recipients', 'persons', '<id>', 'registrations'
    And header Content-Type = 'application/json'
    And request { 
        "reference": "<reference>",
        "startDate": "<startDate>",
        "endDate": "<endDate>",
        "credentialUrl": "<credentialUrl>" 
    }
    When method post
    Then status 201
    And match responseHeaders contains { 'api-version': '#string', 'location': '#string' }
    And match response == 
    { 
        "id": "#string", 
        "reference": "#string", 
        "startDate": "#string", 
        "endDate": "#string", 
        "status": "#string", 
        "credentialUrl": "#string", 
        "suspendedUntil": "#string", 
        "issuedAt": "#string", 
        "createdAt": "#string", 
        "updatedAt": "#string" 
    }

    Examples:
    | id                               | reference | startDate  | endDate    | credentialUrl         |
    | '123e4567-e89b-12d3-a456-426614' | 'ref001'  | '2021-06-1'| '2022-06-1'| 'http://example.com'  |
    | '123e4567-e89b-12d3-a456-426615' | 'ref002'  | '2021-07-1'| '2022-07-1'| 'http://example2.com' |
