# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /recipients/persons/{id}/registrations_get for http method type GET 
# RoostTestHash=318c363c90
# 
# 

# ********RoostGPT********
Feature: Recipient Person

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']
  * def headers = { ApiKeyAuth: '#(authToken)' }

Scenario Outline: Test GET method on /recipients/persons/{id}/registrations endpoint with valid inputs
  Given path '/recipients/persons/', '<id>', '/registrations'
  And params { 'credential-url': '<credential-url>', 'size': '<size>', 'offset': '<offset>' }
  And headers headers
  When method get
  Then status 200
  And match responseHeaders contains { 'api-version': '#string', 'page-size': '#number', 'page-offset': '#number' }
  And match response == { 'total': '#number', 'registrations': '#[] registrations' }
  And match each response.registrations == { 'id': '#uuid', 'reference': '#string', 'startDate': '#string', 'endDate': '#string', 'status': '#string', 'credentialUrl': '#string', 'suspendedUntil': '#string', 'issuedAt': '#string', 'createdAt': '#string', 'updatedAt': '#string' }

Examples:
  | id                                  | credential-url     | size | offset |
  | '123e4567-e89b-12d3-a456-426614174000' | 'http://localhost' | 20   | 0      |

Scenario Outline: Test GET method on /recipients/persons/{id}/registrations endpoint with invalid inputs
  Given path '/recipients/persons/', '<id>', '/registrations'
  And params { 'credential-url': '<credential-url>', 'size': '<size>', 'offset': '<offset>' }
  And headers headers
  When method get
  Then status 400
  And match responseHeaders contains { 'api-version': '#string' }
  And match response == { 'error': '#string', 'description': '#string' }

Examples:
  | id    | credential-url | size | offset |
  | 'invalid-id' | 'http://localhost' | 20   | 0      |
