# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /recipients/branches/{id}_get for http method type GET 
# RoostTestHash=061355b093
# 
# 

# ********RoostGPT********
Feature: Recipient Branch API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
  * def headers = { 'ApiKeyAuth': '#(AUTH_TOKEN)' }

Scenario Outline: Verify GET /recipients/branches/{id} Endpoint
  Given path 'recipients/branches', '<id>'
  And headers headers
  When method get
  Then status 200
  And match response ==
  """
  {
    id: '#string',
    email: '#?string',
    phone: '#?string',
    cocNumber: '#?string',
    cocBranchNumber: '#?string',
    tradeName: '#string',
    tradeNames: '#[] string',
    eoriNumber: '#?string',
    deregistrationDate: '#?string',
    createdAt: '#string',
    updatedAt: '#string'
  }
  """
  And match responseHeaders == { 'api-version': '1.0.0' }

Examples:
  | id |
  | '1234-5678-9012-3456' |
  | '9876-5432-1098-7654' |
  
Scenario: Verify GET /recipients/branches/{id} Endpoint with Invalid ID
  Given path 'recipients/branches', 'invalid-id'
  And headers headers
  When method get
  Then status 400
  And match response == { error: 'error/code', description: 'Descriptive Error Message' }
  And match responseHeaders == { 'api-version': '1.0.0' }

Scenario: Verify GET /recipients/branches/{id} Endpoint without Authorization
  Given path 'recipients/branches', '1234-5678-9012-3456'
  When method get
  Then status 401
  And match response == { error: 'error/code', description: 'Descriptive Error Message' }
  And match responseHeaders == { 'api-version': '1.0.0' }
