# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /recipients/branches/{id}_patch for http method type PATCH 
# RoostTestHash=9caaa2ef96
# 
# 

# ********RoostGPT********
Feature: Recipient Branch

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authHeader = { 'ApiKeyAuth': '#(karate.properties['AUTH_TOKEN'])' }

Scenario Outline: Test recipient branch endpoint

  Given path '/recipients/branches/', '<id>'
  And request {"tradeName": "<tradeName>", "phone": "<phone>", "email": "<email>"}
  And headers authHeader
  When method put
  Then match responseStatus == 200
  And match responseHeaders['api-version'] == '1.0.0'
  And match response.id == '#regex[\\w\\d\\-]{36}'
  And match response.email == '<email>'
  And match response.phone == '<phone>'
  And match response.tradeName == '<tradeName>'

  Examples:
    | id                                    | tradeName | phone       | email           |
    | '3fa85f64-5717-4562-b3fc-2c963f66afa6' | 'TradeCo' | '1234567890' | 'test@trade.co' |
