# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /recipients/persons_post for http method type POST 
# RoostTestHash=b4614c0581
# 
# 

# ********RoostGPT********
Feature: Recipient Person API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def auth_token = karate.properties['AUTH_TOKEN']
  * configure headers = { ApiKeyAuth: '#(auth_token)' }

Scenario Outline: Create new person-recipient of a Credential
  Given path '/recipients/persons'
  And request <requestBody>
  When method post
  Then status 201
  And match response == {birthDate:'#string', birthPlace:'#string', countryCode:'#string', createdAt:'#string', email:'#string', firstName:'#string', houseNumber:'#string', houseNumberPostfix:'#string', id:'#uuid', initials:'#string', lastName:'#string', middleName:'#string', phone:'#string', postalCode:'#string', reference:'#string', updatedAt:'#string'}
  And match header api-version == '1.0.0'
  And match header location == '#string'

Examples:
  | requestBody |
  | { "birthDate": "1980-01-01", "initials": "JD", "lastName": "Doe", "firstName": "John", "middleName": "Middle", "birthPlace": "New York", "phone": "123456789", "email": "john.doe@email.com", "postalCode": "1234AB", "houseNumber": "100", "houseNumberPostfix": "A", "countryCode": "US", "reference": "Ref123" } |
