# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /recipients/persons/{id}_get for http method type GET 
# RoostTestHash=131d25110f
# 
# 

# ********RoostGPT********
Feature: Recipient Person API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * configure headers = { 'Authorization': '#(karate.properties['AUTH_TOKEN'])' }

Scenario Outline: Testing GET method for /recipients/persons/{id} endpoint

  Given path '/recipients/persons', '<id>'
  When method get
  Then status 200
  And match header api-version == '1.0.0'
  And match response contains {id:'#string', initials:'#string', firstName:'#?string', middleName:'#?string', lastName:'#string', birthDate:'#string', birthPlace:'#?string', phone:'#?string', email:'#?string', postalCode:'#?string', houseNumber:'#?string', houseNumberPostfix:'#?string', countryCode:'#?string', reference:'#?string', createdAt:'#string', updatedAt:'#string'}
  And match response.id == '#uuid'
  And match response.initials == '#regex(^[A-Z]{1,6}$)'
  And match response.firstName == '#?regex(^[\\p{L} .'-]{1,50}$)'
  And match response.middleName == '#?regex(^[\\p{L} .'-]{1,20}$)'
  And match response.lastName == '#regex(^[\\p{L} .'-]{2,50}$)'
  And match response.birthDate == '#date'
  And match response.birthPlace == '#?regex(^[\\p{L} .,'-]{2,100}$)'
  And match response.phone == '#?string'
  And match response.email == '#?regex(^(([^<>()[\\]\\\\.,;:\\s@\\\"]+(\\.[^<>()[\\]\\\\.,;:\\s@\\\"]+)*)|(\\\".+\\\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$)'
  And match response.postalCode == '#?regex(^[0-9]{4}[A-Z]{2}$|^[0-9]{4,5}$)'
  And match response.houseNumber == '#?regex(^\\d{1,6}$)'
  And match response.houseNumberPostfix == '#?regex(^[a-zA-Z .,_'-]{0,20}$)'
  And match response.countryCode == '#?regex(^[A-Z]{2}$)'
  And match response.reference == '#?string'
  And match response.createdAt == '#datetime'
  And match response.updatedAt == '#datetime'

Examples:
  | id |
  | '123e4567-e89b-12d3-a456-426614174000' |
  | '123e4567-e89b-12d3-a456-426614174001' |
  | '123e4567-e89b-12d3-a456-426614174002' |
