# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /recipients/persons_get for http method type GET 
# RoostTestHash=aa0a5d4980
# 
# 

# ********RoostGPT********
Feature: Recipient Person API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def auth_token = karate.properties['AUTH_TOKEN']
  * def headers = { ApiKeyAuth: '#(auth_token)' }

Scenario Outline: Get Recipient Persons
  Given path '/recipients/persons'
  And params { size: '#(size)', offset: '#(offset)', name: '#(name)', birth_date: '#(birth_date)' }
  And headers headers
  When method get
  Then status 200
  And match response headers contains { api-version: '#string', page-size: '#number', page-offset: '#number' }
  And match response contains { total: '#number', persons: '#[] object' }

Examples:
  | size | offset | name   | birth_date |
  | 20   | 0      | 'John' | '1990-01-01' |
  | 50   | 10     | 'Doe'  | '1980-12-12' |
  | 25   | 5      | 'Jane' | '2000-11-11' |

Scenario: Get Recipient Persons with Invalid Parameters
  Given path '/recipients/persons'
  And params { size: 'invalid', offset: 'invalid', name: 12345, birth_date: 'invalid-date' }
  And headers headers
  When method get
  Then status 400
  And match response headers contains { api-version: '#string' }
  And match response contains { error: '#string', description: '#string' }

Scenario: Get Recipient Persons without Authentication
  Given path '/recipients/persons'
  And params { size: 20, offset: 0, name: 'John', birth_date: '1990-01-01' }
  When method get
  Then status 401
  And match response headers contains { api-version: '#string' }
  And match response contains { error: '#string', description: '#string' }
