# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /recipients/persons/{id}_delete for http method type DELETE 
# RoostTestHash=819791060f
# 
# 

# ********RoostGPT********
Feature: Recipient Person API

Background:
* def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
* url urlBase
* def authToken = karate.properties['AUTH_TOKEN']
* configure headers = { ApiKeyAuth: '#(authToken)' }

Scenario Outline: Get Recipient Person by ID
Given path '/recipients/persons/', '<id>'
When method get
Then status 200
And match responseHeaders contains { 'api-version': '#string' }
And match responseHeaders['api-version'] == '1.0.0'

Examples:
| id |
| '123e4567-e89b-12d3-a456-426614174000' |
| '123e4567-e89b-12d3-a456-426614174001' |

Scenario Outline: Handle error scenarios
Given path '/recipients/persons/', '<id>'
When method get
Then status <statusCode>
And match responseHeaders contains { 'api-version': '#string' }
And match responseHeaders['api-version'] == '1.0.0'
And match response contains { error: '#string', description: '#string' }

Examples:
| id                               | statusCode |
| '123e4567-e89b-12d3-a456-426614174002' | 400        |
| '123e4567-e89b-12d3-a456-426614174003' | 401        |
