# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /registrations/{id}_patch for http method type PATCH 
# RoostTestHash=3512d7d6f0
# 
# 

# ********RoostGPT********
Feature: Registrations

Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
    * def headers = { 'Authorization': '#(AUTH_TOKEN)', 'Content-Type': 'application/json' }

Scenario Outline: Test /registrations/{id} endpoint

    Given path 'registrations', id
    And headers headers
    And request { 'reference': '<reference>', 'revoked': '<revoked>', 'suspendedUntil': '<suspendedUntil>', 'endDate': '<endDate>' }
    When method PUT
    Then status 200
    And assert responseHeaders['api-version'] == '1.0.0'
    And match response == { 'id': '#string', 'reference': '#string', 'startDate': '#string', 'endDate': '#string', 'status': '#string', 'credentialUrl': '#string', 'suspendedUntil': '#string', 'issuedAt': '#string', 'createdAt': '#string', 'updatedAt': '#string', 'recipient': { 'id': '#string', 'name': '#string', 'type': '#string' } }

    Examples:
        | id                                  | reference   | revoked | suspendedUntil | endDate    |
        | '123e4567-e89b-12d3-a456-426614174000' | 'TestRef'  | false   | '2022-12-31'   | '2022-12-31' |
        | '123e4567-e89b-12d3-a456-426614174001' | 'TestRef1' | true    | '2022-12-31'   | '2022-12-31' |
