# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /registrations/{id}_delete for http method type DELETE 
# RoostTestHash=2c75b43156
# 
# 

# ********RoostGPT********
Feature: Registrations API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
  * configure headers = { ApiKeyAuth: '#(AUTH_TOKEN)' }

Scenario Outline: Test GET /registrations/{id}
  Given path 'registrations', '<id>'
  When method GET
  Then match responseHeaders['api-version'] == '1.0.0'
  And match responseStatus == 200
  
  Examples:
    | id                                   |
    | '123e4567-e89b-12d3-a456-426614174000' |

Scenario Outline: Test GET /registrations/{id} with invalid id
  Given path 'registrations', '<id>'
  When method GET
  Then match responseHeaders['api-version'] == '1.0.0'
  And match responseStatus == 400
  And match $response == {description: '#string', error: '#regex ^error/.*'}
  
  Examples:
    | id |
    | 'invalid-id' |

Scenario Outline: Test GET /registrations/{id} without authorization
  Given path 'registrations', '<id>'
  And configure headers = { ApiKeyAuth: '' }
  When method GET
  Then match responseHeaders['api-version'] == '1.0.0'
  And match responseStatus == 401
  And match $response == {description: '#string', error: '#regex ^error/.*'}
  
  Examples:
    | id |
    | '123e4567-e89b-12d3-a456-426614174000' |
