# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /registrations/{id}_get for http method type GET 
# RoostTestHash=f67303cb4b
# 
# 

# ********RoostGPT********
Feature: Test Registrations API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Test GET /registrations/{id}
  * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
  * configure headers = {ApiKeyAuth: '#(AUTH_TOKEN)'}

  Given path 'registrations', '<id>'
  When method get
  Then status 200
  And match responseHeaders contains { 'api-version': '#string' }
  And match response ==
    """
    {
      "createdAt": '#string',
      "credentialUrl": '#string',
      "endDate": '#string',
      "id": '#string',
      "issuedAt": '#string',
      "recipient": {
        "id": '#string',
        "name": '#string',
        "type": '#string'
      },
      "reference": '#string',
      "startDate": '#string',
      "status": '#string',
      "suspendedUntil": '#string',
      "updatedAt": '#string'
    }
    """

Examples:
  | id                                  |
  | '3fa85f64-5717-4562-b3fc-2c963f66afa6' |

Scenario Outline: Test GET /registrations/{id} with invalid id
  Given path 'registrations', '<id>'
  When method get
  Then status 400
  And match responseHeaders contains { 'api-version': '#string' }
  And match response ==
    """
    {
      "error": '#string',
      "description": '#string'
    }
    """

Examples:
  | id     |
  | '1234' |

Scenario Outline: Test GET /registrations/{id} without authorization
  * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
  * configure headers = {ApiKeyAuth: '#(AUTH_TOKEN)'}
  And remove headers['ApiKeyAuth']

  Given path 'registrations', '<id>'
  When method get
  Then status 401
  And match responseHeaders contains { 'api-version': '#string' }
  And match response ==
    """
    {
      "error": '#string',
      "description": '#string'
    }
    """

Examples:
  | id                                  |
  | '3fa85f64-5717-4562-b3fc-2c963f66afa6' |
