# ********RoostGPT********

# Test generated by RoostGPT for test karateTest2April using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /registrations_get for http method type GET 
# RoostTestHash=5a542f8139
# 
# 

# ********RoostGPT********
Feature: Registrations API Test

Background: 
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authHeader = karate.properties['AUTH_TOKEN'] || 'placeholder_token'
    * configure headers = { 'ApiKeyAuth': '#(authHeader)' }

Scenario Outline: Validate GET /registrations endpoint
    Given path '/registrations'
    And params { size: '<size>', offset: '<offset>', 'recipient-id': '<recipient_id>', 'credential-url': '<credential_url>' }
    When method GET
    Then status <status_code>
    And def responseHeaders = responseHeaders
    And match responseHeaders contains { 'api-version': '#string', 'page-size': '#number', 'page-offset': '#number' }
    And def responseBody = response
    And match responseBody contains { 'total': '#number', 'registrations': '#array' }
    And match each responseBody.registrations contains { 'id': '#string', 'reference': '#string', 'startDate': '#string', 'endDate': '#string', 'status': '#string', 'credentialUrl': '#string', 'suspendedUntil': '#string', 'issuedAt': '#string', 'createdAt': '#string', 'updatedAt': '#string', 'recipient': { 'id': '#string', 'name': '#string', 'type': '#string' } }

    Examples:
        | size | offset | recipient_id               | credential_url              | status_code |
        | 20   | 0      | 'f47ac10b-58cc-4372-a567'  | 'http://example.com'        | 200         |
        | 50   | 10     | 'a47ac10b-58cc-4372-a567'  | 'http://anotherexample.com' | 200         |
        | 10   | 5      | 'b47ac10b-58cc-4372-a567'  | 'http://yetanother.com'     | 200         |
        | 30   | 0      | 'c47ac10b-58cc-4372-a567'  | 'http://andanother.com'     | 200         |
        | 40   | 10     | 'd47ac10b-58cc-4372-a567'  | 'http://onemore.com'        | 200         |
